CC=gcc
CC_FLAGS= -Wall -pedantic -std=c89 -ansi
NAME=fmax2sum
SRCDIR=./src
SRC=$(SRCDIR)/fmax2sum.c

all: 
	$(CC) $(SRC) $(CC_FLAGS) -o $(NAME)

# -----------------------------------------------------------------------	
clean:
	rm  -f $(NAME)

