CC=gcc
CC_FLAGS= -pedantic -std=c89 -ansi
NAME=indentifiers-long
SRCDIR=./src
SRC=$(SRCDIR)/indentifiers-long.c

all: 
	$(CC) $(SRC) $(CC_FLAGS) -o $(NAME)

# -----------------------------------------------------------------------	
clean:
	rm  -f $(NAME)

