CC=gcc
CC_FLAGS= -Wall -pedantic -std=c89 -ansi
NAME=unishift
SRCDIR=./src
SRC=$(SRCDIR)/unishift.c

all: 
	$(CC) $(SRC) $(CC_FLAGS) -o $(NAME)

# -----------------------------------------------------------------------	
clean:
	rm  -f $(NAME)

