.TH DEL-MTIME-WTEMP.SH 1 "2014-02-17" "0.0.1" "file processing"

.SH ИМЯ

del-mtime-wtemp.sh \- Удаляет все файлы с указанным суффиксом, к которым
не было обращений указанное число дней.

.SH ОБЗОР

\fBdel-mtime-wtemp.sh\fP ? | -h | --help

\fBdel-mtime-wtemp.sh\fP <\fIпапка\fP> <\fIдни\fP> [\fIсуффикс\fP]

.SH ОПИСАНИЕ

Из указанной \fIдиректории\fP удаляет все файлы
с указанным \fIсуффиксом\fP, к которым не было обращений
указанное число \fIдней\fP.
Если в качестве первого аргумента указан символ  \fI?\fP
или  \fI-h\fP  или  \fI--help\fP , то выводится описание программы.
Если не указан суффикс файла, то он считается пустой строкой,
и операции производятся со всеми файлами.
Перед каждым удалением у пользователя запрашивается подтверждение.

.SH ПРИМЕРЫ

При вызове команды \fB`\&./del-mtime-wtemp.sh /home/ 4'\fP будут удалены
все файлы в папке \fI./home/\fP, которые старше четырех дней.

\fB`\&./del-mtime-wtemp.sh ./ 4 .c'\fP удалит исходные коды на Си
в текущей директории и поддиректориях.

.SH ФАЙЛЫ
.sp

del-mtime-wtemp.sh
del-mtime-wtemp.man
del-mtime-simple.sh
past-files.sh

.SH АВТОРЫ
Александ Балес (студент 8O-101Б МАИ, 2014)
и Илья Никитин (преп. каф. 806 МАИ) <w@w-495.ru>

Организация: Московский Авиационный Институт,
Национальный Исследовательский Университет

