CC=gcc
CC_FLAGS= -pedantic -std=c89 -ansi
NAME=in-non-decreasing
SRCDIR=./src
SRC=$(SRCDIR)/in-non-decreasing.c

all: 
	$(CC) $(SRC) $(CC_FLAGS) -o $(NAME)

# -----------------------------------------------------------------------	
clean:
	rm  -f $(NAME)

