CC=gcc
CC_FLAGS= -Wall -pedantic -std=c89 -ansi
NAME=curr-prev-letters
SRCDIR=./src
SRC=$(SRCDIR)/curr-prev-letters.c

all: 
	$(CC) $(SRC) $(CC_FLAGS) -o $(NAME)

# -----------------------------------------------------------------------	
clean:
	rm  -f $(NAME)

