CC=gcc
CC_FLAGS= -Wall -pedantic -std=c89 -lm -ansi
NAME=cp3example1
SRCDIR=./src
SRC=$(SRCDIR)/cp3example1.c

all: 
	$(CC) $(SRC) $(CC_FLAGS) -o $(NAME)

# -----------------------------------------------------------------------	
clean:
	rm  -f $(NAME)

