CC=gcc
CC_FLAGS= -Wall -pedantic -std=c89 -lm -ansi
NAME=big-solid
SRCDIR=./src
SRC=$(SRCDIR)/big-solid.c

all: 
	$(CC) $(SRC) $(CC_FLAGS) -o $(NAME)

# -----------------------------------------------------------------------	
clean:
	rm  -f $(NAME)

