CC=gcc
CC_FLAGS= -pedantic -std=c89 -ansi
NAME=yosets
SRCDIR=./src
SRC=$(SRCDIR)/sets.c

all: 
	$(CC) $(SRC) $(CC_FLAGS) -o $(NAME)

# -----------------------------------------------------------------------	
clean:
	rm  -f $(NAME)

